In [1]:
import numpy as np



In [2]:
my_list=[1,2,3,4,5,6]

print(my_list)

[1, 2, 3, 4, 5, 6]


In [3]:
type(my_list)

list

# CONVERTING LIST INTO AN ARRAY

In [4]:
arr=np.array(my_list)

print(arr)

[1 2 3 4 5 6]


# MULTINESTED ARRAY

In [7]:
my_list_1=[1,2,3,4,5]

my_list_2=[6,7,8,9,10]

my_list_3=[11,12,13,14,15]

multinested_arr=np.array([my_list_1,my_list_2,my_list_3])

print(multinested_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


# TO KNOW THE MULTINESTED ARRAY SHAPE

In [8]:
multinested_arr.shape 

(3, 5)

# TO RESHAPE THE MULTINESTED ARRAY

In [9]:
multinested_arr.reshape(5,3)                                   # Reshaping into 5 rows and 3 columns

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# SLICING IN NUMPY

In [11]:
print(arr)

[1 2 3 4 5 6]


In [12]:
arr[3]

4

In [13]:
arr[0]

1

# INDEXING IN NUMPY

In [14]:
arr[0:3]

array([1, 2, 3])

In [15]:
arr[1:4]

array([2, 3, 4])

In [16]:
print(multinested_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [17]:
multinested_arr[0:2,2:4]

array([[3, 4],
       [8, 9]])

In [18]:
multinested_arr[1:,0:3]

array([[ 6,  7,  8],
       [11, 12, 13]])

# GENERATING RANDOM NUMBERS THROUGH NUMPY

In [20]:
random_arr=np.arange(0,10, step=1)                 # 10 is exclusive

random_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
random_arr=np.arange(1,25, step=2)

random_arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# LINSPACE - USED WHEN WE NEED MANY ELEMENTS LIKE 50 OR 100 OR MORE.

In [22]:
np.linspace(1,20,70)                  # 70 elements will be there between 1 and 20

array([ 1.        ,  1.27536232,  1.55072464,  1.82608696,  2.10144928,
        2.37681159,  2.65217391,  2.92753623,  3.20289855,  3.47826087,
        3.75362319,  4.02898551,  4.30434783,  4.57971014,  4.85507246,
        5.13043478,  5.4057971 ,  5.68115942,  5.95652174,  6.23188406,
        6.50724638,  6.7826087 ,  7.05797101,  7.33333333,  7.60869565,
        7.88405797,  8.15942029,  8.43478261,  8.71014493,  8.98550725,
        9.26086957,  9.53623188,  9.8115942 , 10.08695652, 10.36231884,
       10.63768116, 10.91304348, 11.1884058 , 11.46376812, 11.73913043,
       12.01449275, 12.28985507, 12.56521739, 12.84057971, 13.11594203,
       13.39130435, 13.66666667, 13.94202899, 14.2173913 , 14.49275362,
       14.76811594, 15.04347826, 15.31884058, 15.5942029 , 15.86956522,
       16.14492754, 16.42028986, 16.69565217, 16.97101449, 17.24637681,
       17.52173913, 17.79710145, 18.07246377, 18.34782609, 18.62318841,
       18.89855072, 19.17391304, 19.44927536, 19.72463768, 20.  

# RANDOM.RAND: IN CASE OF random.rand THE RANGE IS FROM 0 TO 1 BY DEFAULT AND THE RANDOM ELEMENTS THAT WE GET ARE FLOATING POINT NUMBERS.

In [23]:
np.random.rand()

0.8903331870690822

In [25]:
np.random.rand(5,6)                # 5 rows and 6 columns

array([[0.79136448, 0.8745782 , 0.23254376, 0.53421212, 0.00986523,
        0.69008612],
       [0.02862882, 0.43635653, 0.21836018, 0.19360042, 0.31232585,
        0.98480021],
       [0.49628373, 0.90032557, 0.13003432, 0.65009476, 0.96955575,
        0.72903591],
       [0.85722027, 0.68249594, 0.14719213, 0.82547136, 0.42227436,
        0.16205385],
       [0.01374927, 0.09432134, 0.02191237, 0.16477435, 0.08853842,
        0.18296395]])

# RANDOM.RANDINT(): WE CAN SPECIFY THE RANGE AND THE NO OF ELEMENTS IN THE RANGE. THE NUMBERS YOU GET ARE INTEGER NUMBERS.

In [27]:
np.random.randint(3,25,10)              # 3 to 25 is the range specified and the number of elements in this range is 10  # where 25 is exclusive

array([15,  4,  6, 12, 15, 24, 21,  6,  7,  3])